### ISSUE TITLE
Lesson 03: Error Compiling Templates

### ISSUE THREAD

**Issue by maiya-22** [maiya-22/learning-repo__learn-11ty-from-scratch#2]
I followed the instructions in Lesson 3 ([link here](https://learneleventyfromscratch.com/lesson/3.html#what-is-nunjucks)), but there is an error compiling the templates:

On this repo's branch [Lesson-03](https://github.com/maiya-22/learning-repo__learn-11ty-from-scratch/tree/Lesson-03)
**commit where error is occuring:** [e2764](https://github.com/maiya-22/learning-repo__learn-11ty-from-scratch/tree/e273bb74fa1a6796aa6d06fa660321646d8e2764)

Error: 
`[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for layouts/home.html: _includes (via Error)
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for layouts/home.html: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:101:13)
[11ty]     at TemplateLayoutPathResolver.init (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:70:28)
[11ty]     at new TemplateLayoutPathResolver (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:21:10)
[11ty]     at new TemplateLayout (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:20)
[11ty]     at TemplateLayout.getTemplate (/Users/…/earning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateLayout.js:56:20)
[11ty]     at Template.getLayout (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/Template.js:147:27)
[11ty]     at Template.getData (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/Template.js:376:25)
[11ty]     at async TemplateMap.add (/Users/…/learning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateMap.js:65:16)
[11ty]     at async Promise.all (index 2)
[11ty]     at async TemplateWriter._createTemplateMap (/Users/…/earning-repo__learn-11ty-from-scratch/node_modules/@11ty/eleventy/src/TemplateWriter.js:325:5)
[11ty] Wrote 0 files in 0.04 seconds (v2.0.0)`

**Comment by maiya-22** [comment]
It was a type-o in the config.
Make sure the config file says this:

```
module.exports = config => {
    return {
        markdownTemplateEngine: 'njk',
        dataTemplateEngine: 'njk',
        htmlTemplateEngine: 'njk',
        dir: {
          input: 'src',
          output: 'dist'
        }
    };
  };
```
